# Generated by Django 5.2.11 on 2026-02-19 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_institution_reportingyear_usertype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
